-- use foreign key
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities(id INT AUTO_INCRIMENT PRIMARY KEY NOT NULL UNIQUE, state_id INT NOT NULL FOREIGN KEY (state_id) REFERENCES state(id), name VARCHAR(256));
